// 英文描述到中文的映射（用于 lang_zh 字段）
const WEATHER_DESC_TO_CHINESE: Record<string, string> = {
    "Clear": "晴",
    "Sunny": "晴",
    "Partly cloudy": "少云",
    "Cloudy": "多云",
    "Overcast": "阴",
    "Mist": "轻雾",
    "Patchy rain possible": "局部下小雨",
    "Patchy snow possible": "局部下小雪",
    "Patchy sleet possible": "局部有雨夹雪",
    "Patchy freezing drizzle possible": "局部有冻毛毛雨",
    "Thundery outbreaks possible": "可能打雷",
    "Blowing snow": "小雪",
    "Blizzard": "暴雪",
    "Fog": "雾",
    "Freezing fog": "冻雾",
    "Patchy light drizzle": "局部毛毛雨",
    "Light drizzle": "毛毛雨",
    "Freezing drizzle": "冻毛毛雨",
    "Heavy freezing drizzle": "大冻毛毛雨",
    "Patchy light rain": "局部小雨",
    "Light rain": "小雨",
    "Moderate rain at times": "有时中雨",
    "Moderate rain": "中雨",
    "Heavy rain at times": "有时大雨",
    "Heavy rain": "大雨",
    "Light freezing rain": "小冻雨",
    "Moderate or heavy freezing rain": "中或大冻雨",
    "Light sleet": "小雨夹雪",
    "Moderate or heavy sleet": "中或大雨夹雪",
    "Patchy light snow": "局部小雪",
    "Light snow": "小雪",
    "Patchy moderate snow": "局部中雪",
    "Moderate snow": "中雪",
    "Patchy heavy snow": "局部大雪",
    "Heavy snow": "大雪",
    "Ice pellets": "冰丸",
    "Light rain shower": "小阵雨",
    "Moderate or heavy rain shower": "中或大阵雨",
    "Torrential rain shower": "暴阵雨",
    "Light sleet showers": "小阵雨夹雪",
    "Moderate or heavy sleet showers": "中或大阵雨夹雪",
    "Light snow showers": "小阵雪",
    "Moderate or heavy snow showers": "中或大阵雪",
    "Patchy light rain with thunder": "局部小雷阵雨",
    "Moderate or heavy rain with thunder": "中或大雷阵雨",
    "Patchy light snow with thunder": "小雷阵雪",
    "Moderate or heavy snow with thunder": "中或大雷阵雪",
};


export default function conditionsToChinese(conditions: string): string {

    return WEATHER_DESC_TO_CHINESE[conditions];
};
